name: Run PetStore API Automation Suite in GitHub Actions

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11      
        distribution: 'temurin'

    - name: Build Maven Project
      run: | 
        mvn -B package --file pom.xml  

        # Set the path of the HTML report folder
        REPORT_FOLDER="./target"

        # Create a staging directory and copy the entire report folder
        mkdir -p staging
        cp -r $REPORT_FOLDER staging
    
    - name: Archive HTML report
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: staging
